image: ruby:2.7.1

pipelines:
  default:
    - parallel:
      - step:
          name: Checking Dependencies
          script:
            - bundle install
      - step:
          name: Lint code
          script:
            - ruby -wc **/*.rb
  branches:
    master:
      - step:
          name: Running Rspec Tests
          script:
            - bundle exec rspec
      - step:
          name: Running Migrations
          script:
            - bundle exec rake db:migrate