image: ruby:2.7.1

definitions:
  caches:
    bundler: vendor/bundle
  services:
    mysql:
      image: mysql:5
      variables:
        MYSQL_DATABASE: foof_test
        MYSQL_ROOT_PASSWORD: $DB_TEST_PASSWORD
  steps:
    - step: &syntax-check
        name: Checking Ruby Syntax
        script:
          - ruby -wc **/*.rb
    - step: &pre-build
        name: Checking Dependencies & Running Rspec Tests
        caches:
          - bundler
        script:
          - bundle config set path 'vendor/bundle'
          - bundle install
          - RAILS_MASTER_KEY=$TEST_MASTER_KEY RAILS_ENV=test bundle exec rake db:create
          - RAILS_MASTER_KEY=$TEST_MASTER_KEY RAILS_ENV=test bundle exec rake db:migrate
          - RAILS_MASTER_KEY=$TEST_MASTER_KEY RAILS_ENV=test bundle exec rspec
        services: 
          - mysql

pipelines:
  branches:
    master:
      - step: *syntax-check
      - step: *pre-build
