image: ruby:2.7.1

definitions:
  steps:
    - step: &syntax-check
        name: Checking Ruby Syntax
        script:
          - ruby -wc **/*.rb
    - step: &pre-build
        name: Checking Dependencies & Running Rspec Tests
        script:
          - bundle install
          - RAILS_MASTER_KEY=$TEST_MASTER_KEY RAILS_ENV=test bundle exec rake db:migrate
          - RAILS_MASTER_KEY=$TEST_MASTER_KEY RAILS_ENV=test bundle exec rspec

pipelines:
  branches:
    master:
      - step: *syntax-check
      - step: *pre-build
