image: ruby:2.7.1

definitions:
  steps:
    - step: &syntax-check
        name: Checking Ruby Syntax
        script:
          - ruby -wc **/*.rb
    - step: &pre-build
        name: Checking Dependencies & Running Rspec Tests
        script:
          - bundle install
          - bundle exec rspec
          - bundle exec rake db:migrate

pipelines:
  branches:
    master:
      - step: *syntax-check
      - step: *pre-build
