image: ruby:2.7.1

definitions:
  steps:
    - step: &dependencies
        name: Checking Dependencies
        script:
          - bundle install
    - step: &lint-code
        name: Lint code
        script:
          - ruby -wc **/*.rb
    - step: &rspec
        name: Running Rspec Tests
        script:
          - bundle exec rspec
    - step: &migrations
        name: Running Migrations
        script:
          - bundle exec rake db:migrate

pipelines:
  branches:
    master:
      - parallel:
        - step: *dependencies
        - step: *lint-code
      - step: *rspec
      - step: *migrations
